// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtTh6PQLLAlTDG4Xpq6Es66FeLY2laJw',
    appId: '1:878059006658:web:63cae3877e3d8cdceb695b',
    messagingSenderId: '878059006658',
    projectId: 'video-player-304ab',
    authDomain: 'video-player-304ab.firebaseapp.com',
    storageBucket: 'video-player-304ab.appspot.com',
    measurementId: 'G-DP1CVH7900',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLeFblNMJ57heltczJ9i-oe4x0I4Ik2is',
    appId: '1:878059006658:android:07e6ab6e3e083c7deb695b',
    messagingSenderId: '878059006658',
    projectId: 'video-player-304ab',
    storageBucket: 'video-player-304ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0z9TrFfnteb3SrWFkZ1L0WgrYLmgqWw',
    appId: '1:878059006658:ios:3656409f1fe6d30eeb695b',
    messagingSenderId: '878059006658',
    projectId: 'video-player-304ab',
    storageBucket: 'video-player-304ab.appspot.com',
    iosBundleId: 'com.example.videoPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH0z9TrFfnteb3SrWFkZ1L0WgrYLmgqWw',
    appId: '1:878059006658:ios:c14cca5a6d5573deeb695b',
    messagingSenderId: '878059006658',
    projectId: 'video-player-304ab',
    storageBucket: 'video-player-304ab.appspot.com',
    iosBundleId: 'com.example.videoPlayer.RunnerTests',
  );
}
